[package]
edition = "2018"
name = "lightcycles"
version = "0.1.0"

[dependencies.simple]
path = "../simple"

[dependencies]
rand = "0.8.4"
x264 = {version = "0.1.0", git = "https://github.com/rust-av/x264-rs"}

[profile.release]
lto = true
