[package]
edition = "2018"
name = "simple"
version = "0.1.0"

[dependencies]
byteorder = "1.4"
x264-sys = "0.2.0"

[[bin]]
name = "simple"
src = "src/main.rs"

[lib]
name = "simple"
src = "src/lib.rs"
